hobeetInc/hobeet

src/app/(pages)/(auth)/auth/callback/InsertUserInfo/page.tsx, src/app/(pages)/(auth)/auth/callback/route.ts
- **✅ 작업 사항**
- 로그인 시 callback에서 zustand store에 set하기 위한 페이지 생성
- **📌 변경 사항**
- **🧑‍💻 기타**
=> fix: auth.callback 수정 #11

src/app/(pages)/(auth)/auth/callback/route.ts, src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
- **✅ 작업 사항**
- 회원가입 로직에서 회원가입 후 attend 테이블에 유저아이디 추가
- **📌 변경 사항**
- **🧑‍💻 기타**
=> fix: 회원가입 로직 수정 및 attend 테이블에 유저아이디 추가

src/app/Footer.tsx
=> fix: Footer 수정

src/app/(pages)/(mypage)/_api/supabase.ts, src/app/(pages)/(mypage)/mypage/profile/page.tsx, src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
> #29 
- 마이페이지 > 내가 찜한 모임 페이지에서 내가 찜한 모임 모아보기
- 화면에 데이터 뿌려지기는 하는데 vscode상에서 타입 에러 발생합니다.
=> feat: 내가 찜한 모임 모아보기 구현 #29

src/app/(pages)/(categoryList)/_api/supabase.ts, src/app/(pages)/(categoryList)/_components/CategoryList.tsx, src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx, src/app/Header.tsx, src/components/CategorySlider.tsx, src/components/RegularClubList.tsx
=> feat: 카테고리별 리스트 출력 기능 구현 #32

src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx, src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx, src/app/api/payment/route.ts, src/app/approvemembers/page.tsx, src/components/regularClubJoinButton.tsx, src/utils/regularclubjoin/_api/supabase.ts, src/utils/regularclubjoin/join.ts
> #30 
> 1. 에그 클럽 가입 연결 및 로직 수정
=> fix:정기 모임 가입 승인/승인이 필요하지 않는 부분 로직 수정/#30

src/app/(pages)/(mypage)/_api/supabase.ts, src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx, src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
> ex) close #55
> 마이페이지 내가 결제한 목록 타입 잘못된 부분 수정
=> fix: 마이페이지 내가 결제한 목록 버그 수정 #55

src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
> ex) #49 
> clubId를 secondId로 바꾸기
=> fix: secondId 값으로 수정 #49

src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx, src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx, src/app/api/payment/route.ts
=> fix: 배포주소 변경 #58

src/app/(pages)/(auth)/signin/page.tsx, src/app/(pages)/(categoryList)/_components/CategoryList.tsx, src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx, src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx, src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx, src/app/layout.tsx, src/app/metadata.ts, src/app/page.tsx
> ex) #75
> rootLayout 조건부 랜더링
=> style: rootLayout 조건부 랜더링 #75

src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx, src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx, src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx, src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx, src/app/Footer.tsx, src/app/page.tsx
> #89
> Footer,layout Text컴포넌트 적용 및 불필요한 콘솔로그 삭제
=> style: Footer,layout Text컴포넌트 적용 및 불필요한 콘솔로그 삭제 #89

src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
> #89
> 검색 인기 모임 리스트 margin값 변경
=> style: 검색 인기 모임 리스트 margin값 변경 #89

src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx, src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx, src/app/api/payment/route.ts
=> build: 배포url 적용 #89

src/app/page.tsx
> #89
> 메인페이지 이미지 가운데 정렬안된 문제 해결
=> style: 메인페이지 이미지 가운데 정렬안된 문제 해결 #89

src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx, src/app/(pages)/(categoryList)/_components/CategoryList.tsx, src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx, src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx, src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx, src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx, src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx, src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx, src/app/api/payment/route.ts, src/app/error.tsx, src/app/layout.tsx, src/components/uiComponents/VerticalContentsListLarge.tsx
=> style: 미비된 디자인 적용 #89

src/app/(pages)/(categoryList)/_components/CategoryList.tsx, src/components/CategorySlider.tsx
=> fit: 카테고리페이지 버그 수정

src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
=> fix: 회원가입 프로필 이미지 크기 수정

src/app/store/useScreenSizeStore.ts, src/components/uiComponents/ResponsiveDesign/ScreenSizeInitializer.tsx
> #101 
> 해상도에 따라 조건부 컴포넌트 구현을 위해 store 생성
=> 해상도에 따라 조건부 컴포넌트 구현을 위해 store 생성

src/app/(pages)/(chat)/chat/_components/OneTimeClubChattingRoomPage.tsx, src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
=> fix: Link태그 a태그로 변경

src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx, src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
=> fix: 뒤로가기 막기 성공......#76

src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx, src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx, src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx, src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx, src/app/api/payment/route.ts, src/app/page.tsx
=> fix: 버그 수정

src/app/(pages)/(categoryList)/_components/CategoryList.tsx, src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx, src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx, src/app/Footer.tsx, src/components/myclublistcontent/ClubListContent.tsx
> ex) #76 
> 푸터 위치 올리고 영향가는 페이지 마진바텀 더 줌
=> fix: 푸터 위치 및 마진바텀 수정

src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
=> fix: 카테고리 무한 api 호출 문제 해결

.gitignore, next.config.mjs, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/app/api/sentry-example-api/route.ts, src/app/global-error.tsx, src/app/sentry-example-page/page.tsx, src/instrumentation.ts, yarn.lock
=> add: sentry 설정

next.config.mjs
=> feat: 카카오톡 이미지 못불러오는거 오류 고침 #121

src/app/globals.css
> ex) #이슈번호, #이슈번호 , close #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- Fix border line issues on chat room.
- Restore global css apply on last PR
=> Fix CSS error on chat room

src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx, src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
> #125
> 
채팅방 바텀 마진 mb-6 => mb-10으로 변경
=> style: 채팅방 바텀 마진 변경 #125

.pnp.cjs, src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx, src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx, src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx, src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx, src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx, src/app/(pages)/(mypage)/mypage/profile/page.tsx, src/app/(pages)/(mypage)/mypage/profile/profileUpdate/page.tsx, src/app/(pages)/(mypage)/mypage/profile/wishClubList/page.tsx
> #170 
> 마이페이지, 결제 전/후 페이지 이미지 최적화
=> style: 마이페이지, 결제 전/후 페이지 이미지 최적화 #170
